name: Build and test

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install & build
        run: npm install && npx spago build

      - name: Test
        run: npx spago test
